version: '3.5'

services: 
  interestRateAPI:
    image: interest_rate_api
    build:
      context: .
      dockerfile: InterestCalculatorBackend.InterestRateAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - interest-calculator-network
  interestCalculatorWebAPI:
    image: interest_calculator_webapi
    build:
      context: .
      dockerfile: InterestCalculatorBackend.WebAPI/Dockerfile
    depends_on:
      - "interestRateAPI"
    links:
      - "interestRateAPI"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 5000:80
    networks:
      - interest-calculator-network

networks:
  interest-calculator-network:
    driver: bridge